import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Footer from "@/components/Header/Footer";
import Header from "@/components/Header/Header";
import Navbar from "@/components/Header/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      

      <head>

        
      <meta name="robots" content="noindex, nofollow"></meta>
       <style>
@import url('https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&family=Montserrat:ital,wght@0,100..900;1,100..900&family=Roboto:ital,wght@0,100..900;1,100..900&display=swap');
</style>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >


        <Navbar />
        <Header />

        {children}

        <Footer />
      </body>
    </html>
  );
}
